### ISSUE TITLE
Is it possible to implement it in preview mode?

### ISSUE THREAD

**Issue by glitchlover** [mgmeyers/obsidian-contextual-typography#1]
hope you are fine. Waiting for your ans. thank you.

**Comment by mgmeyers** [comment]
@glitchlover could you clarify what you mean? This plugin only works in preview mode at the moment.

**Comment by glitchlover** [comment]
Sorry for the typing mistake, actually I meant for edit mode 😅. I am trying to make a plugin for editor mode by myself. As you have worked something similar to my plugin, I was just asking if it is possible to apply it in editor mode? Thank you for the patience

**Comment by mgmeyers** [comment]
Ah! I see. This I'm not sure of. Once obsidian's WYSIWYG editor is available it might be more doable, but right now, I think codemirror has enough limitations to make this a difficult—if not impossible—task.

**Comment by glitchlover** [comment]
thanks!
