### ISSUE TITLE
Breaks image size formatting when 'Readable line length' is enabled

### ISSUE THREAD

**Issue by nilssrvd** [mgmeyers/obsidian-contextual-typography#11]
The plugin blocks image size formatting from working when '**_Readable line length_**' is enabled in Obsidian's settings. An instruction to resize an image, such as "**![[image.jpg|100]]**", will not change the size. 

In addition, it causes small images to cover the entire width of the note, these cannot be made smaller and they look obviously pixelated. When '**_Readable line length_**' is disabled the image size formatting synthax works again. 

This report is specifically for the Ars Magna theme, I don't know if it has the same effect on other themes (I assume it does).

**Comment by HyperEpsilon** [comment]
Just wanted to add, with only Contextual Typography installed, I am not able to reproduce.

I installed the Ars Magna theme specifically to test, but my embedded images still resize correctly.

**Comment by mgmeyers** [comment]
@nilssrvd This is likely a theme issue rather than an issue with this plugin, as this plugin doesn't modify styling in any way, but allows theme designers to have more control over how content is styled. Maybe report this as a bug in the Ars Magna theme?
