### ISSUE TITLE
Missing text in pdf export

### ISSUE THREAD

**Issue by MartinKorz** [mgmeyers/obsidian-contextual-typography#14]
I do not know how this unexpected behaviour is created, but when I activate contextual typography I find that exported pdf files regularly miss seemingly random paragraphs of the document's plain text.

Deactivating the plugin and restarting Obsidian leads to complete pdf text again.

I am not sure whether the problem is actually created by contextual typography as I have quite a number of plugins activated. It might also be that there is some incompatibility to other plugins.

**Comment by chenmaoran** [comment]
I also encountered the same problem.  If the document has a large number of images, the export function is almost unavailable.  contextual typography is a great plugin, I can't live without it, but I also need to use the function of exporting PDF, please fix this bug, thanks.

**Comment by mgmeyers** [comment]
@MartinKorz @chenmaoran I haven't been able to reproduce this in my tests. Does this happen with obsidian's default theme? Also, does it happen in a sandbox vault (click on help, then open sandbox vault)?

**Comment by chenmaoran** [comment]
@mgmeyers  I created a new Vault with only the contextual typography plugin and corresponding CSS for your reference.  In addition, the compressed package also contains the exported stamp widePDF file.

Download link：https://www.dropbox.com/t/FwjWqI2bVHKfcZyS

**Comment by tim-hilde** [comment]
I've just encountered the same issue. No need for specific CSS styling. Only the plugin is needed to lose text in the sandbox vault. I've attached the file I wanted to export.

[Expose Promotion.md](https://github.com/mgmeyers/obsidian-contextual-typography/files/9289555/Expose.Promotion.md)

**Comment by chenmaoran** [comment]
Still hope the author can fix this soon. Thank you!

**Comment by mgmeyers** [comment]
Hey all. Finally figured out what this issue was. This should be fixed now. Let me know if you still run into issues.

**Comment by MartinKorz** [comment]
My test pdfs look good now, thank you!
