### ISSUE TITLE
Add attributes for images and tables

### ISSUE THREAD

**Issue by kepano** [mgmeyers/obsidian-contextual-typography#5]
The attribute/classes provided by the plugin doesn't match the content in some cases: 

- `img` tags appear as a `p`
- Dataview `tables` appear as a `div`
- Dataview `ul` appear as a `div`

It seems that in both cases this is due to the fact that Obsidian wraps those elements in the aforementioned tags, however it would be useful to have the correct tags available.

**Comment by mgmeyers** [comment]
@kepano So, I've added a bunch of new info pertaining to embeds:

<img width="762" alt="Screen Shot 2021-11-21 at 12 47 29 PM" src="https://user-images.githubusercontent.com/2694747/142778403-ca0184e9-c2d0-4333-b679-b76ef202a765.png">

Handling dataview elements doesn't seem like it'll be doable, though. Dataview elements aren't populated by the time they reach this plugin, so I have no way of knowing if the element is a table or a list. It seems the best I can do for now is surface the language attribute of the codeblock.

<img width="738" alt="Screen Shot 2021-11-21 at 12 50 11 PM" src="https://user-images.githubusercontent.com/2694747/142778481-1764e8e7-cc91-49de-8b3f-a0da07b95de1.png">

Let me know if all this works for you.

**Comment by kepano** [comment]
I will experiment and report back!

**Comment by kepano** [comment]
Seems to be working great for my purposes. I will open a new issue if I see anything new comes up. Thanks!
