### ISSUE TITLE
Contextual Typography cuts off icons in Obsidian Banner plugin

### ISSUE THREAD

**Issue by janpeeters70** [mgmeyers/obsidian-contextual-typography#9]
I don't know if the problem is with Contextual Typography or how Obsidian Banner plugin has been coded but when they are both active the icons of Obsidian Banner plugin are cut off. Maybe you can have look at this issue: https://github.com/noatpad/obsidian-banners/issues/27.

**Comment by mgmeyers** [comment]
Hi @janpeeters70, this looks like an issue with the minimal theme and not this plugin. Contextual typography doesn't actually modify the CSS in any way! Hope you were able to git it figured out
